### ISSUE TITLE
Broken link for slide deck

### ISSUE THREAD

**Issue by douglyuckling** [ogazitt/global-appsec-2023#1]
The link to the slide deck in `README.md` no longer works. Looks like the new/correct link should be https://static.sched.com/hosted_files/owasp2023globalappsecwashin/8a/Global%20AppSec%202023%20-%20Fixing%20Broken%20Access%20Control%20-%20Final.pptx

**Comment by ogazitt** [comment]
Thanks @douglyuckling!  Fixed, along with updates to make this work with Topaz v3 (released today!)
